#!/bin/sh

echo '[git hook] executing spotless apply before commit'

# store all staged files
files=$(git diff --name-only --staged)

# get project basedir
BASEDIR=$(dirname "$0")

# concatenate staged files
for i in $files
do
  STAGED_FILES=$STAGED_FILES$BASEDIR/$i,
  STAGED_FILES_SPACE_SEPARATED="$STAGED_FILES_SPACE_SEPARATED $i"
done

echo "Files space separated: $STAGED_FILES_SPACE_SEPARATED"
echo "Files comma separated: $STAGED_FILES"

# run spotless only for staged files
mvn spotless:apply "-DspotlessFiles=$STAGED_FILES" --quiet

# add updates after spotless
git add --update $STAGED_FILES_SPACE_SEPARATED

# run spotless check maven
mvn spotless:check "-DspotlessFiles=$STAGED_FILES" --quiet

# store the last exit code in a variable
RESULT=$?

# run one more time if failed
if [ "$RESULT" -ne "0" ]; then
  mvn spotless:apply "-DspotlessFiles=$STAGED_FILES" --quiet
  git add --update $STAGED_FILES_SPACE_SEPARATED
  mvn spotless:check "-DspotlessFiles=$STAGED_FILES" --quiet
  RESULT=$?
fi

# return the 'mvn spotless:check' exit code
exit $RESULT
