SOLR_HTTP_URL=$1
SOLR_COLLECTION=$2
SOLR_COLLECTION_TODAY=$3

echo "Create alias $SOLR_COLLECTION for $SOLR_COLLECTION_TODAY"
curl -s """$SOLR_HTTP_URL"/admin/collections?action=CREATEALIAS\&name="$SOLR_COLLECTION"\&collections="$SOLR_COLLECTION_TODAY"""
