package org.gbif.registry.metasync.util;

/**
 * Constants used by the Metadata synchroniser.
 */
public final class Constants {

  public static final String ABCD_12_SCHEMA = "http://www.tdwg.org/schemas/abcd/1.2";
  public static final String ABCD_206_SCHEMA = "http://www.tdwg.org/schemas/abcd/2.06";
  /**
   * Namespace used for machine tags generated by the metadata synchroniser.
   */
  public static final String METADATA_NAMESPACE = "metasync.gbif.org";

  // BEGIN: "Names" used in Machine Tags
  public static final String DIGIR_CODE = "code";
  public static final String DIGIR_MAX_SEARCH_RESPONSE_RECORDS = "maxSearchResponseRecords";
  public static final String CONCEPTUAL_SCHEMA = "conceptualSchema";
  public static final String DATE_LAST_UPDATED = "dateLastUpdated";
  public static final String DECLARED_COUNT = "declaredCount";
  public static final String INSTALLATION_VERSION = "version";
  public static final String ARCHIVE_ORIGIN = "archiveOrigin";
  // END: "Names" used in Machine Tags

  private Constants() {
    throw new UnsupportedOperationException("Can't initialize class");
  }

}
